apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  labels:
    run: private-registry
  name: private-registry
  namespace: default
spec:
  containers:
  - image: registry:2
    imagePullPolicy: IfNotPresent
    name: private-registry
    ports:
    - containerPort: 5000
      protocol: TCP
    volumeMounts:
    - name: volume-mount
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
